#index:
#    path: /
#    controller: App\Controller\DefaultController::index

get_employees_for_shift:
    path: '/api/employeesforshift'
    methods: ['GET']
    defaults:
        _controller: '\App\Controller\EmployeeController::getForShiftAction'
        _api_resource_class: '\App\Resource\Model\EmployeesForShift\EmployeesForShiftOutputDTO'
        _api_collection_operation_name: 'employeesforshift'
    
